# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Ruby"]
    branches: [ main ]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: lambda-ruby-sample-codebuild
          buildspec-override: buildspec.yaml
          env-vars-for-codebuild: |
            REPOSITORY_URI
        env:
          REPOSITORY_URI: ${{ secrets.REPOSITORY_URI }}
      - name: Deploy lambda
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws lambda update-function-code --function-name LambdaRubySample --image-uri $REPOSITORY_URI:$IMAGE_TAG

