name: CI

on:
  workflow_run:
    workflows: ["Ruby"]
    branches: [ main ]
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: lambda-ruby-sample-codebuild
          buildspec-override: buildspec.yaml
          env-vars-for-codebuild: |
            REPOSITORY_URI
        env:
          REPOSITORY_URI: ${{ secrets.REPOSITORY_URI }}
      - name: Deploy lambda
        env:
          IMAGE_TAG: ${{ github.sha }}
          REPOSITORY_URI: ${{ secrets.REPOSITORY_URI }}
        run: |
          aws lambda update-function-code --function-name LambdaRubySample --image-uri $REPOSITORY_URI:$IMAGE_TAG

